2022-01-10 14:02:31,109	INFO monitor.py:527 -- Starting monitor using ray installation: /home/reza/anaconda3/lib/python3.8/site-packages/ray/__init__.py
2022-01-10 14:02:31,109	INFO monitor.py:528 -- Ray version: 1.9.0
2022-01-10 14:02:31,109	INFO monitor.py:529 -- Ray commit: 92599d9127e228fe8d0a2d94ca75754ec21c4ae4
2022-01-10 14:02:31,109	INFO monitor.py:530 -- Monitor started with command: ['/home/reza/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py', '--logs-dir=/home/reza/Dropbox/Prog/MERA/temp/session_2022-01-10_14-02-29_530256_11572/logs', '--redis-address=131.215.21.210:6379', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--redis-password=5241590000000000', '--monitor-ip=131.215.21.210']
2022-01-10 14:02:31,114	INFO monitor.py:192 -- Starting autoscaler metrics server on port 44217
2022-01-10 14:02:31,114	INFO monitor.py:206 -- Monitor: Started
2022-01-10 14:02:31,137	INFO autoscaler.py:214 -- StandardAutoscaler: {'cluster_name': 'default', 'max_workers': 0, 'upscaling_speed': 1.0, 'docker': {}, 'idle_timeout_minutes': 0, 'provider': {'type': 'readonly', 'use_node_id_as_ip': True}, 'auth': {}, 'available_node_types': {'ray.head.default': {'resources': {}, 'node_config': {}, 'max_workers': 0}}, 'head_node_type': 'ray.head.default', 'file_mounts': {}, 'cluster_synced_files': [], 'file_mounts_sync_continuously': False, 'rsync_exclude': [], 'rsync_filter': [], 'initialization_commands': [], 'setup_commands': [], 'head_setup_commands': [], 'worker_setup_commands': [], 'head_start_ray_commands': [], 'worker_start_ray_commands': [], 'head_node': {}, 'worker_nodes': {}}
2022-01-10 14:02:31,138	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 14:02:31.138635 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:


Demands:
 (no resource demands)
2022-01-10 14:02:36,144	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 14:02:36.144788 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_67f5a9d96c5cfce5b67ff73a4aa5e45685dd778eddaebca97d586e0e
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.280 GiB memory
 0.00/7.640 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 14:02:41,148	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 14:02:41.148711 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_67f5a9d96c5cfce5b67ff73a4aa5e45685dd778eddaebca97d586e0e
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.280 GiB memory
 0.00/7.640 GiB object_store_memory

Demands:
 (no resource demands)
