2022-01-10 13:46:57,445	INFO monitor.py:527 -- Starting monitor using ray installation: /home/reza/anaconda3/lib/python3.8/site-packages/ray/__init__.py
2022-01-10 13:46:57,445	INFO monitor.py:528 -- Ray version: 1.9.0
2022-01-10 13:46:57,445	INFO monitor.py:529 -- Ray commit: 92599d9127e228fe8d0a2d94ca75754ec21c4ae4
2022-01-10 13:46:57,445	INFO monitor.py:530 -- Monitor started with command: ['/home/reza/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py', '--logs-dir=/home/reza/Dropbox/Prog/MERA/temp/session_2022-01-10_13-46-55_876037_5882/logs', '--redis-address=131.215.21.210:6379', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--redis-password=5241590000000000', '--monitor-ip=131.215.21.210']
2022-01-10 13:46:57,449	INFO monitor.py:192 -- Starting autoscaler metrics server on port 44217
2022-01-10 13:46:57,449	INFO monitor.py:206 -- Monitor: Started
2022-01-10 13:46:57,473	INFO autoscaler.py:214 -- StandardAutoscaler: {'cluster_name': 'default', 'max_workers': 0, 'upscaling_speed': 1.0, 'docker': {}, 'idle_timeout_minutes': 0, 'provider': {'type': 'readonly', 'use_node_id_as_ip': True}, 'auth': {}, 'available_node_types': {'ray.head.default': {'resources': {}, 'node_config': {}, 'max_workers': 0}}, 'head_node_type': 'ray.head.default', 'file_mounts': {}, 'cluster_synced_files': [], 'file_mounts_sync_continuously': False, 'rsync_exclude': [], 'rsync_filter': [], 'initialization_commands': [], 'setup_commands': [], 'head_setup_commands': [], 'worker_setup_commands': [], 'head_start_ray_commands': [], 'worker_start_ray_commands': [], 'head_node': {}, 'worker_nodes': {}}
2022-01-10 13:46:57,475	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:46:57.475175 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:


Demands:
 (no resource demands)
2022-01-10 13:47:02,480	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:02.480808 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:07,484	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:07.484855 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:12,489	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:12.489909 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:17,496	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:17.496668 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:22,501	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:22.501428 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:27,504	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:27.504766 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:32,508	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:32.508736 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:37,514	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-10 13:47:37.514048 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a2555d49f488493edef00cca156fb4ec3d7cc8824153fc1d1f300bf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/15.831 GiB memory
 0.00/7.916 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-10 13:47:42,070	ERROR monitor.py:398 -- Error in monitor loop
NoneType: None
2022-01-10 13:47:42,070	ERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1641851262.070478188","description":"Error received from peer ipv4:131.215.21.210:35079","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Socket closed","grpc_status":14}"
>
2022-01-10 13:47:42,070	ERROR gcs_utils.py:142 -- Connecting to gcs failed. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1641851262.070478188","description":"Error received from peer ipv4:131.215.21.210:35079","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Socket closed","grpc_status":14}"
>
