2022-01-28 12:02:57,649	INFO monitor.py:527 -- Starting monitor using ray installation: /home/reza/anaconda3/lib/python3.8/site-packages/ray/__init__.py
2022-01-28 12:02:57,649	INFO monitor.py:528 -- Ray version: 1.9.0
2022-01-28 12:02:57,649	INFO monitor.py:529 -- Ray commit: 92599d9127e228fe8d0a2d94ca75754ec21c4ae4
2022-01-28 12:02:57,649	INFO monitor.py:530 -- Monitor started with command: ['/home/reza/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py', '--logs-dir=/home/reza/Dropbox/Prog/MERA/temp/session_2022-01-28_12-02-56_080277_35693/logs', '--redis-address=131.215.21.210:6379', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--redis-password=5241590000000000', '--monitor-ip=131.215.21.210']
2022-01-28 12:02:57,653	INFO monitor.py:192 -- Starting autoscaler metrics server on port 44217
2022-01-28 12:02:57,653	INFO monitor.py:206 -- Monitor: Started
2022-01-28 12:02:57,677	INFO autoscaler.py:214 -- StandardAutoscaler: {'cluster_name': 'default', 'max_workers': 0, 'upscaling_speed': 1.0, 'docker': {}, 'idle_timeout_minutes': 0, 'provider': {'type': 'readonly', 'use_node_id_as_ip': True}, 'auth': {}, 'available_node_types': {'ray.head.default': {'resources': {}, 'node_config': {}, 'max_workers': 0}}, 'head_node_type': 'ray.head.default', 'file_mounts': {}, 'cluster_synced_files': [], 'file_mounts_sync_continuously': False, 'rsync_exclude': [], 'rsync_filter': [], 'initialization_commands': [], 'setup_commands': [], 'head_setup_commands': [], 'worker_setup_commands': [], 'head_start_ray_commands': [], 'worker_start_ray_commands': [], 'head_node': {}, 'worker_nodes': {}}
2022-01-28 12:02:57,678	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-28 12:02:57.678580 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:


Demands:
 (no resource demands)
2022-01-28 12:03:02,685	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-28 12:03:02.685348 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_a3633cf6d2151fd57674ad1a7c39f81bbb51b9c59fbe942d2cd84e0b
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/10.192 GiB memory
 0.00/5.096 GiB object_store_memory

Demands:
 (no resource demands)
